In [1]:
import numpy as np

In [4]:
vector = np.array([1,2,3,4,5])
equal_to_two_and_five = (vector == 2) & (vector == 5)
print(equal_to_two_and_five)

[False False False False False]


In [6]:
vector = np.array([1,2,3,4,5])
equal_to_two_and_five = (vector == 2) | (vector == 5)
print(equal_to_two_and_five)

[False  True False False  True]


In [7]:
vector[equal_to_two_and_five] = 0
print(vector)

[1 0 3 4 0]


* array可以进行数据类型转换，以及按行或列进行求和

In [14]:
vector = np.array(["1","2","3","4"])
print(vector.dtype)
print(vector)
vector = vector.astype(float)
print(vector.dtype)
print(vector)

<U1
['1' '2' '3' '4']
float64
[1. 2. 3. 4.]


In [15]:
vector = np.array([1,2,3,40])
print(vector.min())

1


In [16]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix.sum(axis = 1)

array([ 6, 15, 24])

In [17]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix.sum(axis = 0)

array([12, 15, 18])