In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
             [4,5,6]])
print(a)
print('-------------')
b = np.exp(a)
print(b)
print('-------------')
c = np.sqrt(a)
print(c)

[[1 2 3]
 [4 5 6]]
-------------
[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]
-------------
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [3]:
a = np.floor(10 * np.random.random((3,4)))
print(a)

[[5. 1. 9. 3.]
 [2. 2. 7. 8.]
 [2. 6. 4. 3.]]


In [5]:
b = a.ravel()
print(b)

[5. 1. 9. 3. 2. 2. 7. 8. 2. 6. 4. 3.]


In [6]:
c = b.reshape((3,-1))
print(c)

[[5. 1. 9. 3.]
 [2. 2. 7. 8.]
 [2. 6. 4. 3.]]


In [7]:
c.shape = (6,2)
print(c)

[[5. 1.]
 [9. 3.]
 [2. 2.]
 [7. 8.]
 [2. 6.]
 [4. 3.]]


In [9]:
print(c.T)

[[5. 9. 2. 7. 2. 4.]
 [1. 3. 2. 8. 6. 3.]]


* numpy.hstack 横向拼接 用于增加特征数
* numpy.vstack 纵向拼接 用于增加样本数

In [12]:
a = np.floor(10 * np.random.random((2,2)))
b = np.floor(10 * np.random.random((2,2)))
print(a)
print('-------------')
print(b)
print('-------------')
print(np.hstack((a,b)))
print('-------------')
print(np.vstack((a,b)))

[[4. 2.]
 [2. 2.]]
-------------
[[2. 4.]
 [5. 4.]]
-------------
[[4. 2. 2. 4.]
 [2. 2. 5. 4.]]
-------------
[[4. 2.]
 [2. 2.]
 [2. 4.]
 [5. 4.]]


* numpy.hsplit 横向裁剪，也可以指向位置
* numpy.vsplit 纵向裁剪

In [18]:
a = np.floor(10 * np.random.random((2,6)))
print(a)
print('-------------')
print(np.hsplit(a,3))
print('-------------')
print(np.hsplit(a,(2,3)))
print('-------------')
print(np.vsplit(a.T,3))

[[2. 4. 9. 4. 5. 8.]
 [5. 3. 9. 7. 6. 0.]]
-------------
[array([[2., 4.],
       [5., 3.]]), array([[9., 4.],
       [9., 7.]]), array([[5., 8.],
       [6., 0.]])]
-------------
[array([[2., 4.],
       [5., 3.]]), array([[9.],
       [9.]]), array([[4., 5., 8.],
       [7., 6., 0.]])]
-------------
[array([[2., 5.],
       [4., 3.]]), array([[9., 9.],
       [4., 7.]]), array([[5., 6.],
       [8., 0.]])]
