In [1]:
import numpy as np

* 复制，两者共用一块内存

In [10]:
a = np.arange(12)
b = a
print(a)
print(b)
print(id(a))
print(id(b))
b[4] = 100
print(a)
print(id(a))
print(id(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
90820480
90820480
[  0   1   2   3 100   5   6   7   8   9  10  11]
90820480
90820480


* 浅复制，两者有不同的指向，但共用的是一套值

In [14]:
c = a.view()
print(c is a)
print(id(a))
print(id(c))
c = c.reshape((3,4))
print(c)
c[2,1] = 200
print(a)
print(id(a))
print(id(c))

False
90820480
95503344
[[  0   1   2   3]
 [100   5   6   7]
 [  8 200  10  11]]
[  0   1   2   3 100   5   6   7   8 200  10  11]
90820480
95502864


* copy函数

In [16]:
d = a.copy()
d[4] = 300
print(a)
print(d)

[  0   1   2   3 100   5   6   7   8 200  10  11]
[  0   1   2   3 300   5   6   7   8 200  10  11]


In [18]:
a = np.arange(0,10,2)
print(a)
b = np.tile(a,(2,2))
print(b)

[0 2 4 6 8]
[[0 2 4 6 8 0 2 4 6 8]
 [0 2 4 6 8 0 2 4 6 8]]


In [29]:
data  = np.sin(np.arange(20).reshape(4,5))
print(data)
ind = data.argmax(axis=0)  #axis=0表示纵向获取，每列最大值的索引
print(ind)
print(data[ind,range(data.shape[1])])

[[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
 [-0.95892427 -0.2794155   0.6569866   0.98935825  0.41211849]
 [-0.54402111 -0.99999021 -0.53657292  0.42016704  0.99060736]
 [ 0.65028784 -0.28790332 -0.96139749 -0.75098725  0.14987721]]
[3 0 0 1 2]
[0.65028784 0.84147098 0.90929743 0.98935825 0.99060736]


In [33]:
a = np.array([[6,3,4],[4,4,5]])
b = np.sort(a,axis=1)
print(b)

[[3 4 6]
 [4 4 5]]


In [36]:
a = np.array([1,6,7,3,2])
j = np.argsort(a)
print(j)
print(a[j])

[0 4 3 1 2]
[1 2 3 6 7]
